version: "3"
services:
  master:
    image: mpolatcan/hadoop:ubuntu-2.9.0
    container_name: master
    hostname: master
    environment:
      - HADOOP_NODE_TYPE=namenode
      - DFS_REPLICATION=2
    ports:
      - 8080:16010
      - 50070:50070
      - 50090:50090
      - 50075:50075
      - 1988:1988
      - 8042:8042
      - 8088:8088

  slave:
    image: mpolatcan/hadoop:ubuntu-2.9.0
    environment:
      - HADOOP_NODE_TYPE=datanode
      - FS_HOSTNAME=master
      - YARN_RM_HOSTNAME=master
      - DFS_REPLICATION=2
    links:
      - master
